### ISSUE TITLE
gorm@1.25.7 is not compatible with postgres@1.5.6 driver. 

### ISSUE THREAD

**Issue by 7adidaz** [pilinux/gorest#167]
**Describe the bug**
trying to run `go run example/main.go` i get an error: `pq: got 2 parameters but the statement requires 1`, investigating this, leads to this [solution](https://github.com/go-gorm/gorm/issues/5409#issuecomment-1151234551). 

**To Reproduce**
- normal setup provided in `readme.md` 
- `go run example/main.go`

- **Expected behavior**
- migrate & run the server. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.10
 - postsql: 16.2

**Comment by pilinux** [comment]
@7adidaz Thanks for the valuable input! I always check mysql, redis, and mongo thoroughly before releasing an update. For postgres, I only did first migration test which always worked but didn't test with rerun. Surprisingly, the last functioning postgres driver version is `gorm.io/driver/postgres v1.4.0`!

**Comment by pilinux** [comment]
@7adidaz I overlooked the issue for the latest postgres driver config. It is now fixed in release [v1.6.30](https://github.com/pilinux/gorest/releases/tag/v1.6.30) 👍🏻

**Comment by 7adidaz** [comment]
thank you! :)
