### ISSUE TITLE
go-orm ? official package ?

### ISSUE THREAD

**Issue by Paul75** [piLinux/GoREST#4]
Hello,

It is only a question : 

I see you import "github.com/jinzhu/gorm"
and not gorm.io/gorm

It is the same ?

Thanks

**Comment by piLinux** [comment]
I am using v1 of gorm `http://v1.gorm.io` and the import should be `github.com/jinzhu/gorm`.

Later, v2 is released and should be imported from `gorm.io/gorm`.

I haven't tested v2 yet, hence cannot confirm whether it is backward compatible or not.
