### ISSUE TITLE
Sqlite3 db connection 

### ISSUE THREAD

**Issue by DevBadi** [piLinux/GoREST#7]
**Describe the bug**
When I select the Sqlite3 DB I get : 

near "CONSTRAINT": syntax error
Auto migration failed!

File : 
AutoMigrate.go

**Comment by piLinux** [comment]
Please disable this function with `//` when you use PostgreSQL or Sqlite3 database.

https://github.com/piLinux/GoREST/blob/c2fe9034f22b073e383cb8965850d9fe9fe7468c/database/migrate/autoMigrate.go#L49

**Comment by DevBadi** [comment]
It is working now. 
Thanks
